### PR TITLE
Patched up your sample

### PR DESCRIPTION
**Pull request by andrewfluck**
It works well now. I'm using a templating language in there as well. I'm gonna do a bit more work.

### CODE REVIEW

**Comment by andrewfluck** [comment]
It uses some ES2015/ES6 features you should use node 6 if you haven't already.

**Comment by andrewfluck** [comment]
@Arthelon you should probably pull

**Comment by Arthelon** [comment]
Your example doesn't seem to be working, the link in your layout points to the root path instead of /main defined in the middleware constructor. Also, could you migrate your nested dependencies to the root package.json and refactor the server so that it can run off the "start-example" script?

EDIT: I see you've patched the error

**Comment by andrewfluck** [comment]
Sure @Arthelon I'll patch up the start script

**Comment by andrewfluck** [comment]
From my testing, it's better to keep the 2 package.json files seperate

**Comment by Arthelon** [comment]
It's debatable. I noticed that __dirname resolves to the root directory since you're running the server with an npm script from there. Make that final patch and I'll merge it in.

**Comment by Arthelon** [comment]
It's debatable. I noticed a small typo in app.set("/views"...). Make that final patch and I'll merge it in.

**Comment by andrewfluck** [comment]
k

**Comment by andrewfluck** [comment]
@Arthelon where is the typo? I can't seem to find it

**Comment by Newtsrock** [comment]
typo*

**Comment by Arthelon** [comment]
Line 12: app.set('/views', path.join(`${__dirname}/views`));

**Comment by andrewfluck** [comment]
I mean everything seems to work fine assuming you are running it from the project dir and are using node 6+

**Comment by andrewfluck** [comment]
Also the library works nicely, I want to give props to you for making it 😄




Everything on my personal site works the way it would if SPF was done on the client side. Everything still transitions smoothly, just like it would (like I said before) if SPF was on the client side.

**Comment by andrewfluck** [comment]
Can you tell me what to correct it to? I can't find it. I may actually be blind :/ Plz halp me...

EDIT: I can see line 12, I'm just not sure where the typo is.

**Comment by Arthelon** [comment]
It's interesting that it works for you. From what I know about express, app.set("/views",...) isn't a valid option and should be set to app.set("views", ...)

**Comment by andrewfluck** [comment]
well I'll change it

**Comment by andrewfluck** [comment]
Changed @Arthelon

**Comment by Arthelon** [comment]
Your original line 13 was correct D:

**Comment by andrewfluck** [comment]
Changed it, it really is interesting how anything works for me.

**Comment by Arthelon** [comment]
Best of luck with your project. Merged.

**Pull request merged**
